version: '2'

services:

  crypto-terminal:
    image: dalijolijo/crypto-terminal
    container_name: crypto-terminal
    environment:
      VIRTUAL_HOST: 9e98d434-ec06-49d3-8dba-041726e407a8.pub.cloud.scaleway.com
      LETSENCRYPT_HOST: 9e98d434-ec06-49d3-8dba-041726e407a8.pub.cloud.scaleway.com
      LETSENCRYPT_EMAIL: test@gmx.net

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
